// <auto-generated />
namespace muitos_para_muitos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PRIMEIRO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PRIMEIRO));
        
        string IMigrationMetadata.Id
        {
            get { return "202206220349036_PRIMEIRO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
